# Generated by Django 6.0.3 on 2026-03-07 17:18

from django.db import migrations, models


def seed_sites(apps, schema_editor):
    site_model = apps.get_model("donations", "Site")
    site_names = [
        "Englewood",
        "Hackensack",
        "Mahwah",
        "Paterson - Catholic Charities",
        "Pop-up Distribution",
        "Ringwood",
        "Saddle Brook",
        "Warehouse (Mahwah)",
        "Warehouse (Saddle Brook)",
    ]
    for name in site_names:
        site_model.objects.get_or_create(name=name, defaults={"is_active": True})


def unseed_sites(apps, schema_editor):
    site_model = apps.get_model("donations", "Site")
    site_model.objects.filter(
        name__in=[
            "Englewood",
            "Hackensack",
            "Mahwah",
            "Paterson - Catholic Charities",
            "Pop-up Distribution",
            "Ringwood",
            "Saddle Brook",
            "Warehouse (Mahwah)",
            "Warehouse (Saddle Brook)",
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.RunPython(seed_sites, unseed_sites),
    ]
