# Generated by Django 6.0.3 on 2026-03-12 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0005_normalize_donation_site_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='donor_type',
            field=models.CharField(choices=[('Civic', 'Civic'), ('Religious', 'Religious'), ('Corporate', 'Corporate'), ('Individual', 'Individual')], default='Individual', max_length=16),
        ),
    ]
