# Generated by Django 6.0.3 on 2026-03-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0006_donation_donor_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='donation',
            name='cash_check',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cash/Check $'),
        ),
        migrations.AddField(
            model_name='donation',
            name='gift_cards',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Gift Cards $'),
        ),
        migrations.AddField(
            model_name='donation',
            name='num_bags',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='# of Bags'),
        ),
        migrations.AddField(
            model_name='donation',
            name='num_boxes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='# of Boxes'),
        ),
        migrations.AddField(
            model_name='donation',
            name='other_donation',
            field=models.CharField(blank=True, max_length=255, verbose_name='Other Donation'),
        ),
        migrations.AddField(
            model_name='donation',
            name='total_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total Weight (lbs)'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donor_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donor_type',
            field=models.CharField(blank=True, choices=[('Civic', 'Civic'), ('Religious', 'Religious'), ('Corporate', 'Corporate'), ('Individual', 'Individual')], default='Individual', max_length=16),
        ),
        migrations.AlterField(
            model_name='donation',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
