# Generated by Django 6.0.3 on 2026-03-31 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0007_donation_address_donation_cash_check_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='organization',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
