# Generated by Django 6.0.3 on 2026-04-21 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0008_donation_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donor_type',
            field=models.CharField(blank=True, choices=[('Anonymous', 'Anonymous'), ('Civic', 'Civic'), ('Religious', 'Religious'), ('Corporate', 'Corporate'), ('Individual', 'Individual')], default='Individual', max_length=16),
        ),
    ]
